[project]
name = "python-mastery"
version = "0.1.0"
description = "An open source, interactive course delivered via Jupyter Notebooks."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
